### ISSUE TITLE
Check If User Logged In Before Logging Out

### ISSUE THREAD

**Issue by Yiroh** [IssacL891/CSCI-320-Final-Project#36]
Issue previously discussed in discord, but after failing to login into a user, then logging in successfully and doing your business, you logout, then try to quit, but it throws an error when you quit.

>quit
Connection to 127.0.0.1:3307 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.

The Stacktrace:
>org.postgresql.util.PSQLException: Connection to 127.0.0.1:3307 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
        at org.postgresql.Driver.makeConnection(Driver.java:443)
        at org.postgresql.Driver.connect(Driver.java:297)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
        at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:87)
        at com.CSCI32006.CLI.SetupDatabase.logout(SetupDatabase.java:53)
        at com.CSCI32006.CLI.SetupDatabase.quit(SetupDatabase.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.shell.command.invocation.InvocableShellMethod.doInvoke(InvocableShellMethod.java:306)
        at org.springframework.shell.command.invocation.InvocableShellMethod.invoke(InvocableShellMethod.java:232)
        at org.springframework.shell.command.CommandExecution$DefaultCommandExecution.evaluate(CommandExecution.java:227)
        at org.springframework.shell.Shell.evaluate(Shell.java:248)
        at org.springframework.shell.Shell.run(Shell.java:159)
        at org.springframework.shell.jline.InteractiveShellRunner.run(InteractiveShellRunner.java:73)
        at org.springframework.shell.DefaultShellApplicationRunner.run(DefaultShellApplicationRunner.java:65)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:772)
        at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:762)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:760)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:329)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325)
        at com.CSCI32006.CLI.CliApplication.main(CliApplication.java:13)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)
Caused by: java.net.ConnectException: Connection refused: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        
The Spring-Shell.Log:
>1698354601648:help
1698354605847:login
1698354745235:login sbyrde0,"mioANC427)g,po"
1698354757845:login sbyrde0
1698354793770:login sbyrde0 mioANC427)g,po
1698354806976:login mioANC427)g,po
1698354861786:login
1698354866120:help
1698354884228:getTables
1698354888204:getTables user
1698354898226:getTable 1
1698354905951:getTables users
1698354937468:3307
1698354939875:login 3307
1698354982357:login "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKa6nJMvSukR49BQKBngMyLYfZwIJfqljctbKtIj/ErjSYSPOZqpslaxCToab20u21lvLDjQ/P04zj9fgoK4Dj4=";
1698355003405:}
1698355003406:asf
1698355003407:fdg
1698355010405:login "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKa6nJMvSukR49BQKBngMyLYfZwIJfqljctbKtIj/ErjSYSPOZqpslaxCToab20u21lvLDjQ/P04zj9fgoK4Dj4=";
1698355047428:}login "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKa6nJMvSukR49BQKBngMyLYfZwIJfqljctbKtIj/ErjSYSPOZqpslaxCToab20u21lvLDjQ/P04zj9fgoK4Dj4=";
1698355053857:}clear
1698355056426:login "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKa6nJMvSukR49BQKBngMyLYfZwIJfqljctbKtIj/ErjSYSPOZqpslaxCToab20u21lvLDjQ/P04zj9fgoK4Dj4=";
1698355056929:}
1698355867086:stacktrace
1698356209573:logout
1698356212464:help
1698356219736:quit
1698357016490:login "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKa6nJMvSukR49BQKBngMyLYfZwIJfqljctbKtIj/ErjSYSPOZqpslaxCToab20u21lvLDjQ/P04zj9fgoK4Dj4="
1698357032003:login AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKa6nJMvSukR49BQKBngMyLYfZwIJfqljctbKtIj/ErjSYSPOZqpslaxCToab20u21lvLDjQ/P04zj9fgoK4Dj4=
1698357076153:login "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKa6nJMvSukR49BQKBngMyLYfZwIJfqljctbKtIj/ErjSYSPOZqpslaxCToab20u21lvLDjQ/P04zj9fgoK4Dj4=";
1698357115612:logout
1698357136912:login
1698358084729:quit

**Comment by dbo8671** [comment]
Resolved
